S03 us40 main landscape media q
WildCodeSchool/2023-09-JS-Lille-blue-project-2-groupe1-graphiteam pull request #27
Opened 2023-11-09 14:03 UTC by HeleneRamp

2023-11-09 15:05 UTC, Thomas-Nigon approved these changes

2023-11-09 15:19 UTC, fantinerudent requested changes

2023-11-09 15:19 UTC, fantinerudent commented on frontend/src/pages/Homepage/Homepage.scss
> +  // background-image: url("src/assets/bg_main.jpg");
nop

2023-11-09 15:19 UTC, fantinerudent commented on frontend/src/pages/Homepage/Homepage.scss
> +// @media only screen and (orientation:portrait){
nop

2023-11-10 08:49 UTC, fantinerudent approved these changes

2023-11-10 09:11 UTC, merged